name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: GoGet
      run: go get github.com/bitly/go-simplejson && go get github.com/ebfe/keccak && go get github.com/jzelinskie/whirlpool && go get github.com/satori/go.uuid && go get github.com/gorilla/websocket && go get github.com/valyala/fastjson && go get github.com/BurntSushi/toml && go get github.com/atwat/bigoo

    - name: Run
      env:
        user1: ${{secrets.user1}}
        user2: ${{secrets.user2}}
        user3: ${{secrets.user3}}
        pass1: ${{secrets.pass1}}
        pass2: ${{secrets.pass2}}
        pass3: ${{secrets.pass3}}
        bilive: ${{secrets.bilive}}
        yjaddr: ${{secrets.yjaddr}}
        yjkey: ${{secrets.yjkey}}
      run: go build && ./bigoo --user1=${user1} --pass1=${pass1} --user2=${user2} --pass2=${pass2} --user3=${user3} --pass3=${pass3} --bilive=${bilive} --yjaddr=${yjaddr} --yjkey=${yjkey}

